name: model automation
on: 
  push:
jobs:
  installa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            lamanna
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
        working-directory: lamanna
      - run: python model.py
        working-directory: lamanna
  esegui:
    needs: installa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            lamanna
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          cache: 'pip'
      - run: python model.py
        working-directory: lamanna