name: model automation
on: 
  push:
jobs:
  installa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            lamanna
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          cache: 'pip'
          cache-dependency-path: 'lamanna/requirements.txt'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
        working-directory: lamanna
      - run: python model.py
        working-directory: lamanna
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.txt
  esegui:
    needs: installa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            lamanna
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          cache: 'pip'
          cache-dependency-path: 'lamanna/requirements.txt'
      - run: pip install -r requirements.txt
        working-directory: lamanna
      - run: python model.py
        working-directory: lamanna