name: infos
on: 
  push:
jobs:
  versione:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - run: pip --version
  librerie:
    runs-on: ubuntu-latest
    steps:
      - run: pip list