name: infos     #nome
on: 
  push:
jobs:
  versione:     #nome Job
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - run: pip --version
  librerie:
    runs-on: ubuntu-latest
    steps:
      - run: pip list
  filteros:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            lamanna