name: model automation
on: 
  push:
jobs:
  installa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - run: pip install -r /requirements.txt
        working-diretory: lamanna
  esecuzione:
    runs-on: ubuntu-latest
    steps:
      - run: model.py
        working-diretory: lamanna