name: model automation
on: 
  push:
jobs:
  installa:
    runs-on: ubuntu-latest
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'
    - run: pip install -r /requirements.txt
  run:
    runs-on: ubuntu-latest
    - run: x
      working-diretory: ./lamanna