name: model automation
on: 
  push:
jobs:
  installa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            lamanna
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - run: python -m pip install
      - run: pip install -r requirements.txt
        working-directory: lamanna
  esecuzione:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            lamanna
      - run: model.py
        working-directory: lamanna